[project]
name = "app"
version = "0.0.0"
license = "Apache-2.0"
description = ""
authors = [
    { name = "CU Devs Collective", email = "team@centraluniversity.dev" },
]
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21,<1",
    "alembic>=1.19,<2",
    "fastapi>=0.141,<1",
    "httpx2>=2.12,<3",
    "loguru>=0.7,<1",
    "maxapi==1.2.2",
    "psycopg[binary]>=3.3,<4",
    "pydantic>=2.13,<3",
    "pydantic-settings>=2.15,<3",
    "sqlalchemy[asyncio]>=2.0,<3",
    "uvicorn[standard]>=0.52,<1",
]

[dependency-groups]
dev = [
    "openapi-spec-validator==0.9.0",
    "pre-commit==4.6.2",
    "pyright==1.1.411",
    "pyyaml==6.0.3",
    "pytest==9.1.1",
    "pytest-cov==7.1.0",
    "ruff==0.16.4",
]

[project.scripts]
api = "app.api.__main__:main"
bot = "app.bot.__main__:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = ["--strict-config", "--strict-markers"]
testpaths = ["tests"]

[tool.pyright]
venvPath = "."
venv = ".venv"
include = ["src", "tests", "tools", "migrations"]
pythonVersion = "3.13"
typeCheckingMode = "standard"

[tool.coverage.run]
branch = true
source = ["app"]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
allowed-confusables = ["А", "В", "Е", "К", "М", "Н", "О", "Р", "С", "Т", "Х", "а", "е", "о", "р", "с", "у", "х"]
select = [
    "E",
    "F",
    "I",
    "UP",
    "B",
    "SIM",
    "RUF",
]

[tool.ruff.lint.isort]
lines-after-imports = 2
