"""Generate and validate the OpenAPI document from the FastAPI application."""

import argparse
import pathlib
import sys

import openapi_spec_validator
import yaml

from app.api.app import OPENAPI_VERSION, create_app


SPEC_PATH = pathlib.Path(__file__).resolve().parents[1] / "spec/openapi.yaml"


class OpenApiDumper(yaml.SafeDumper):
    def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:
        super().increase_indent(flow, indentless=False)

    def choose_scalar_style(self) -> str:
        style = super().choose_scalar_style()
        return '"' if style == "'" else style


def render_openapi() -> str:
    document = create_app().openapi()
    actual_version = document.get("openapi")
    if actual_version != OPENAPI_VERSION:
        raise ValueError(f"Expected OpenAPI {OPENAPI_VERSION}, generated {actual_version!r}")

    openapi_spec_validator.validate(document)
    yaml_document = yaml.dump(
        document,
        Dumper=OpenApiDumper,
        allow_unicode=True,
        default_flow_style=False,
        indent=2,
        sort_keys=False,
        width=100,
    )
    return "# Code generated by tools/generate_openapi.py. DO NOT EDIT.\n" + yaml_document


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the output document differs from the generated document",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rendered = render_openapi()

    if args.check:
        current = SPEC_PATH.read_text(encoding="utf-8") if SPEC_PATH.exists() else None
        if current != rendered:
            print(f"{SPEC_PATH} is outdated, rerun OpenAPI spec generation", file=sys.stderr)
            return 1
        print(f"Validated {SPEC_PATH} as OpenAPI {OPENAPI_VERSION}")
        return 0

    SPEC_PATH.parent.mkdir(parents=True, exist_ok=True)
    SPEC_PATH.write_text(rendered, encoding="utf-8")
    print(f"Generated {SPEC_PATH} (OpenAPI {OPENAPI_VERSION})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
