// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CallExampleHttpApiData, CallExampleHttpApiErrors, CallExampleHttpApiResponses, GetLivenessData, GetLivenessResponses, GetReadinessData, GetReadinessErrors, GetReadinessResponses } from './types.gen';
import { zCallExampleHttpApiResponse, zGetLivenessResponse, zGetReadinessResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Liveness
 */
export const getLiveness = <ThrowOnError extends boolean = true>(options?: Options<GetLivenessData, ThrowOnError>): RequestResult<GetLivenessResponses, unknown, ThrowOnError, 'data'> => (options?.client ?? client).get<GetLivenessResponses, unknown, ThrowOnError, 'data'>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetLivenessResponse.parseAsync(data),
    responseStyle: 'data',
    url: '/v1/healthz/live',
    ...options
});

/**
 * Readiness
 */
export const getReadiness = <ThrowOnError extends boolean = true>(options?: Options<GetReadinessData, ThrowOnError>): RequestResult<GetReadinessResponses, GetReadinessErrors, ThrowOnError, 'data'> => (options?.client ?? client).get<GetReadinessResponses, GetReadinessErrors, ThrowOnError, 'data'>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetReadinessResponse.parseAsync(data),
    responseStyle: 'data',
    url: '/v1/healthz/ready',
    ...options
});

/**
 * Call External Api
 */
export const callExampleHttpApi = <ThrowOnError extends boolean = true>(options?: Options<CallExampleHttpApiData, ThrowOnError>): RequestResult<CallExampleHttpApiResponses, CallExampleHttpApiErrors, ThrowOnError, 'data'> => (options?.client ?? client).get<CallExampleHttpApiResponses, CallExampleHttpApiErrors, ThrowOnError, 'data'>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCallExampleHttpApiResponse.parseAsync(data),
    responseStyle: 'data',
    url: '/v1/examples/http',
    ...options
});
