// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * Error
 */
export type Error = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
    /**
     * Details
     */
    details?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    error: Error;
};

/**
 * Health
 */
export type Health = {
    /**
     * Status
     */
    status?: 'ok';
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    data: Health;
};

/**
 * HttpExample
 */
export type HttpExample = {
    /**
     * Upstream Id
     */
    upstream_id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Completed
     */
    completed: boolean;
};

/**
 * HttpExampleResponse
 */
export type HttpExampleResponse = {
    data: HttpExample;
};

export type GetLivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/healthz/live';
};

export type GetLivenessResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type GetLivenessResponse = GetLivenessResponses[keyof GetLivenessResponses];

export type GetReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/healthz/ready';
};

export type GetReadinessErrors = {
    /**
     * Service unavailable
     */
    503: ErrorResponse;
};

export type GetReadinessError = GetReadinessErrors[keyof GetReadinessErrors];

export type GetReadinessResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type GetReadinessResponse = GetReadinessResponses[keyof GetReadinessResponses];

export type CallExampleHttpApiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/examples/http';
};

export type CallExampleHttpApiErrors = {
    /**
     * Upstream error
     */
    502: ErrorResponse;
};

export type CallExampleHttpApiError = CallExampleHttpApiErrors[keyof CallExampleHttpApiErrors];

export type CallExampleHttpApiResponses = {
    /**
     * Successful Response
     */
    200: HttpExampleResponse;
};

export type CallExampleHttpApiResponse = CallExampleHttpApiResponses[keyof CallExampleHttpApiResponses];
