// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Error
 */
export const zError = z.object({
    code: z.string(),
    message: z.string(),
    details: z.array(z.record(z.string(), z.unknown())).optional()
});

/**
 * ErrorResponse
 */
export const zErrorResponse = z.object({
    error: zError
});

/**
 * Health
 */
export const zHealth = z.object({
    status: z.enum(['ok']).optional().default('ok')
});

/**
 * HealthResponse
 */
export const zHealthResponse = z.object({
    data: zHealth
});

/**
 * HttpExample
 */
export const zHttpExample = z.object({
    upstream_id: z.int(),
    title: z.string(),
    completed: z.boolean()
});

/**
 * HttpExampleResponse
 */
export const zHttpExampleResponse = z.object({
    data: zHttpExample
});

/**
 * Successful Response
 */
export const zGetLivenessResponse = zHealthResponse;

/**
 * Successful Response
 */
export const zGetReadinessResponse = zHealthResponse;

/**
 * Successful Response
 */
export const zCallExampleHttpApiResponse = zHttpExampleResponse;
